# This was a no longer relevant attempt to ensure that setjmp is linked into
# ld.so after it had been made a member of `$(static-only-routines)'. This
# didn't help since it had to be linked into libc.so too.

# ifeq ($(subdir),elf)
# sysdep-rtld-routines += setjmp
# endif
