ifeq ($(subdir),math)
# See Bug #105130, Comment #2 for why fraiseexcpt.c should be compiled with
# -O0 on E2K. Or with -fno-spec-fp option
CFLAGS-fraiseexcpt.c += -fno-spec-fp

# See Bug #106328, Comment #4 for why s_fma/f/l.c should be compiled with
# -O0 on E2K. Or with -fno-spec-fp option
CFLAGS-s_fmaf.c += -fno-spec-fp
CFLAGS-s_fma.c += -fno-spec-fp
CFLAGS-s_fmal.c += -fno-spec-fp

# See Bug #118896
CFLAGS-k_standardl.c += -fno-spec-fp
CFLAGS-e_expf128.c += -fno-spec-fp
CFLAGS-s_fadd.c += -fno-spec-fp
CFLAGS-s_faddl.c += -fno-spec-fp
CFLAGS-s_daddl.c += -fno-spec-fp
CFLAGS-s_f32addf128.c += -fno-spec-fp
CFLAGS-s_f64addf128.c += -fno-spec-fp
CFLAGS-s_f64xaddf128.c += -fno-spec-fp
CFLAGS-s_fdiv.c += -fno-spec-fp
CFLAGS-s_fdivl.c += -fno-spec-fp
CFLAGS-s_ddivl.c += -fno-spec-fp
CFLAGS-s_f32divf128.c += -fno-spec-fp
CFLAGS-s_f64divf128.c += -fno-spec-fp
CFLAGS-s_f64xdivf128.c += -fno-spec-fp
CFLAGS-s_fmul.c += -fno-spec-fp
CFLAGS-s_fmull.c += -fno-spec-fp
CFLAGS-s_dmull.c += -fno-spec-fp
CFLAGS-s_f32mulf128.c += -fno-spec-fp
CFLAGS-s_f64mulf128.c += -fno-spec-fp
CFLAGS-s_f64xmulf128.c += -fno-spec-fp
CFLAGS-s_fsub.c += -fno-spec-fp
CFLAGS-s_fsubl.c += -fno-spec-fp
CFLAGS-s_dsubl.c += -fno-spec-fp
CFLAGS-s_f32subf128.c += -fno-spec-fp
CFLAGS-s_f64subf128.c += -fno-spec-fp
CFLAGS-s_f64xsubf128.c += -fno-spec-fp

# See Bug #109049, #109054
CFLAGS-e_hypot.c += -fno-rounding-math

CFLAGS-s_ccos.c += -fno-rounding-math
CFLAGS-s_ccosh.c += -fno-rounding-math
CFLAGS-s_cexp.c += -fno-rounding-math
CFLAGS-s_csin.c += -fno-rounding-math
CFLAGS-s_csinh.c += -fno-rounding-math
CFLAGS-s_csqrt.c += -fno-rounding-math

CFLAGS-s_cos.c += -fno-rounding-math
CFLAGS-s_sin.c += -fno-rounding-math
CFLAGS-s_sincos.c += -fno-rounding-math
CFLAGS-s_tan.c += -fno-rounding-math

# To be continued. See Bug #152437
CFLAGS-e_acos.c += -fno-rounding-math
CFLAGS-e_acosf.c += -fno-rounding-math
CFLAGS-e_acosh.c += -fno-rounding-math
CFLAGS-e_acosl.c += -fno-rounding-math
CFLAGS-e_asin.c += -fno-rounding-math
CFLAGS-e_asinf.c += -fno-rounding-math
CFLAGS-e_atan2.c += -fno-rounding-math
CFLAGS-e_atan2f.c += -fno-rounding-math
CFLAGS-e_atan2l.c += -fno-rounding-math
CFLAGS-e_atanh.c += -fno-rounding-math
CFLAGS-e_atanhf.c += -fno-rounding-math
CFLAGS-e_cosh.c += -fno-rounding-math
CFLAGS-e_coshf.c += -fno-rounding-math
CFLAGS-e_exp10.c += -fno-rounding-math
CFLAGS-e_exp10f.c += -fno-rounding-math
CFLAGS-e_exp2.c += -fno-rounding-math
CFLAGS-e_exp2f.c += -fno-rounding-math
CFLAGS-e_exp2l.c += -fno-rounding-math
CFLAGS-e_exp.c += -fno-rounding-math
CFLAGS-e_expf.c += -fno-rounding-math
CFLAGS-e_expl.c += -fno-rounding-math
CFLAGS-e_fmodl.c += -fno-rounding-math
CFLAGS-e_lgamma_r.c += -fno-rounding-math
CFLAGS-e_log10.c += -fno-rounding-math
CFLAGS-e_log10l.c += -fno-rounding-math
CFLAGS-e_log2l.c += -fno-rounding-math
CFLAGS-e_log.c += -fno-rounding-math
CFLAGS-e_logl.c += -fno-rounding-math
CFLAGS-e_pow.c += -fno-rounding-math
CFLAGS-e_powf.c += -fno-rounding-math
CFLAGS-e_powl.c += -fno-rounding-math
CFLAGS-e_remainderl.c += -fno-rounding-math
CFLAGS-e_scalbl.c += -fno-rounding-math
CFLAGS-e_sinh.c += -fno-rounding-math
CFLAGS-e_sinhf.c += -fno-rounding-math
CFLAGS-s_asinh.c += -fno-rounding-math
CFLAGS-s_asinhf.c += -fno-rounding-math
CFLAGS-s_atan.c += -fno-rounding-math
CFLAGS-s_atanf.c += -fno-rounding-math
CFLAGS-s_atanl.c += -fno-rounding-math
CFLAGS-s_cbrt.c += -fno-rounding-math
CFLAGS-s_cbrtf.c += -fno-rounding-math
CFLAGS-s_ccosf.c += -fno-rounding-math
CFLAGS-s_ccoshf.c += -fno-rounding-math
CFLAGS-s_ceill.c += -fno-rounding-math
CFLAGS-s_cexpf.c += -fno-rounding-math
CFLAGS-s_clog.c += -fno-rounding-math
CFLAGS-s_clogf.c += -fno-rounding-math
CFLAGS-s_copysignl.c += -fno-rounding-math
CFLAGS-s_cosf.c += -fno-rounding-math
CFLAGS-s_cosl.c += -fno-rounding-math
CFLAGS-s_csinf.c += -fno-rounding-math
CFLAGS-s_csinhf.c += -fno-rounding-math
CFLAGS-s_erf.c += -fno-rounding-math
CFLAGS-s_erff.c += -fno-rounding-math
CFLAGS-s_expm1.c += -fno-rounding-math
CFLAGS-s_expm1f.c += -fno-rounding-math
CFLAGS-s_expm1l.c += -fno-rounding-math
CFLAGS-s_fabsl.c += -fno-rounding-math
CFLAGS-s_finitel.c += -fno-rounding-math
CFLAGS-s_floorl.c += -fno-rounding-math
CFLAGS-s_fpclassifyl.c += -fno-rounding-math
CFLAGS-s_isinfl.c += -fno-rounding-math
CFLAGS-s_isnanl.c += -fno-rounding-math
CFLAGS-s_ldexpl.c += -fno-rounding-math
CFLAGS-s_llroundl.c += -fno-rounding-math
CFLAGS-s_log1p.c += -fno-rounding-math
CFLAGS-s_log1pf.c += -fno-rounding-math
CFLAGS-s_log1pl.c += -fno-rounding-math
CFLAGS-s_lroundl.c += -fno-rounding-math
CFLAGS-s_nearbyintl.c += -fno-rounding-math
CFLAGS-s_nexttoward.c += -fno-rounding-math
CFLAGS-s_nexttowardf.c += -fno-rounding-math
CFLAGS-s_scalblnl.c += -fno-rounding-math
CFLAGS-s_scalbnl.c += -fno-rounding-math
CFLAGS-s_significandl.c += -fno-rounding-math
CFLAGS-s_sincosf.c += -fno-rounding-math
CFLAGS-s_sincosl.c += -fno-rounding-math
CFLAGS-s_sinf.c += -fno-rounding-math
CFLAGS-s_sinl.c += -fno-rounding-math
CFLAGS-s_tanf.c += -fno-rounding-math
CFLAGS-s_tanh.c += -fno-rounding-math
CFLAGS-s_tanhf.c += -fno-rounding-math
CFLAGS-s_tanl.c += -fno-rounding-math

endif
